### ISSUE TITLE
Account creation worked, but failed

### ISSUE THREAD

**Issue by Taffer** [auroris/City-of-Heroes-Account-Portal#7]
I just tried creating my account, and it doesn't seem to have recorded the correct password. I can't log back into the portal, and I can't log into the game.

I used a max-length (16 character) password of random characters, including \, ., and *. Not sure if:

1. I saved the wrong password (unlikely, I use EnPass to generate and record passwords).
2. There's a length bug somewhere (maybe 15 characters of password got saved in the account?).
3. There's a string escaping bug due to the special characters.
4. magic.gif

Tried using "Taffer" and "taffer" as the user ID, and tried using the full password and the first 15 characters of the password (in case it got truncated).

**Comment by auroris** [comment]
I need more information about the specifics of how you judge account creation failed. Are you still able to login via the portal, but not the client?

A known bug with Tequila / Cream Soda causes it to point you at a valid, but wrong, City of Heroes server. When you attempt to login, you are authenticating with a server you don't actually have an account at.

As an addendum, the work-around to this bug is to manually specify your launch parameters.

**Comment by Taffer** [comment]
In this case, "failed" seems to mean that it created an account for Taffer, but that I can't actually log in to the portal. If I try to register a new account as Taffer, it tells me the account already exists. I'll try specifying launch params by hand to see if that helps.

**Comment by Taffer** [comment]
Confirmed via using Cream Soda's option to specify launch params, and by running Ouroboros.exe by hand with `-project coh -auth coh.ourodev.com`. I get the "invalid account name or password" message.

I could throw together a quick Python script to generate password hashes if that would help; someone with DB access could compare what's in there with the hash I provide.
